server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - https://tinystepscdc.com
                  - https://www.tinystepscdc.com
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                    - "*"
                allow-credentials: true

  data:
    redis:
      host: redis-service
      port: 6379
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: https://tinystepscdc.com/auth

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    hostname: ts-api-gateway
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://ts-service-registry:8761/eureka/

internal:
  api:
    secret: "902ffc52f4ab670361e543008a5f8e86005edadfbc1df36f5cc375b433448aff"
