apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-api-gateway
  template:
    metadata:
      labels:
        app: ts-api-gateway
    spec:
      containers:
        - name: ts-api-gateway
          image: subhankarm2312/ts-api-gateway:ff6076b-20250808063332 # This will be updated by the pipeline          env:
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
            - name: INTERNAL_API_SECRET  # This creates the environment variable
              valueFrom:
                secretKeyRef:
                  name: internal-api-secret   # The name of our new Secret object
                  key: secret-value
          resources:
            requests:
              memory: "128Mi" # Request 256 MiB of memory
              cpu: "100m"        # Request 0.25 of a CPU core
            limits:
              memory: "512Mi" # Limit the pod to a max of 512 MiB
              cpu: "500m"      # Limit the pod to a max of 0.5 of a CPU core
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ts-api-gateway-config
            - secretRef:
                name: ts-user-db-credentials

