apiVersion: v1
kind: Secret
metadata:
  name: ts-api-gateway-secret
type: Opaque
stringData:
  # The key we will reference later
  secret-value: "902ffc52f4ab670361e543008a5f8e86005edadfbc1df36f5cc375b433448aff"
