server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          # The Gateway also validates tokens using the Auth Service's issuer URI
          issuer-uri: http://localhost:8081

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/

internal:
  api:
    secret: "902ffc52f4ab670361e543008a5f8e86005edadfbc1df36f5cc375b433448aff"
